### ISSUE TITLE
account/patch do not properly validate mlchkid

### ISSUE THREAD

**Issue by spotlightishere** [Disconnect24/disguise-api#3]
I don't really need to expand much more on this

![abuse](https://spotlight-thinks-awoo.should-be.legal/c05a33.png)

**Comment by InternalLoss** [comment]
Further adding to this issue: Perhaps check the checksum of the file before patching. If it's not valid, don't patch.

It's very much security by obscurity, but it stops very basic editing of MLID and thus people cant impersonate others with a race attack.

MLID should always be 16 digits between 0 and 9, and passwd and mlchkid you should be making server-side and inserting into the file realistically; don't use the credentials inside the file, make new ones; this also solves the issue of if another server gets hacked, the credentials for that server are hacked but not your server or any other's.

**Comment by spotlightishere** [comment]
> MLID should always be 16 digits between 0 and 9

https://github.com/Disconnect24/disguise-api/blob/180adf04225bdad6f19bdd25b167800055ef741d/utils.go#L62-L75

> passwd and mlchkid you should be making server-side

on account we do, on frontend patch we reuse due to the fact switching between other services is a must right now.

> this also solves the issue of if another server gets hacked, the credentials for that server are hacked but not your server or any other's.

not exactly something i'm happy about, but it's kinda a must...

**Comment by InternalLoss** [comment]
>not exactly something i'm happy about, but it's kinda a must...

May I ask why you're not happy about this?
In theory, if users wish to be able to move between services they can and services should be able to change the credentials of the user accordingly.

**Comment by spotlightishere** [comment]
was responding mid sentence. I'm not happy that I must reuse passwd/mlchkid (which would help security on both ends, and leave one less place to sanitise user input) but if we want to preserve across services (short of forcing a specific homebrew app to be used for us) that's how it'll be.

**Comment by TheMrIron2** [comment]
Whoops wrong button


But yeah, it seems we have to use the same method as RiiConnect24 to maintain cross compatibility...

...unfortunately.

**Comment by spotlightishere** [comment]
We are actually validating mlchkid/passwd compared to RC24, we just can't change them for ourselves.

The entire issue here lies in numerical verification (i.e begins with w, 16 digits 0-9) which should probably be validated with a regex. frontend's structure file should import the main package's structures along with utils to verify all information.

**Comment by TheMrIron2** [comment]
I see - I misinterpreted the issue. However for the frontend it still seems that having RiiConnect24 compatibility is the issue. Perhaps RiiConnect24 could change to fit our system instead of us having to reuse?

**Comment by spotlightishere** [comment]
Short of us syncing credentials that's not possible.

**Comment by InternalLoss** [comment]
RiiConnect24 should have to change to allow passwords to not be the same.
Especially since the current in-dev patcher *does that*, and doesnt read from the CFG itself, I say go for it.

**Comment by spotlightishere** [comment]
To confirm I'm not misreading: you're telling us that the entire issue (short of verification of mlid) isn't needed, because your patcher is going to overwrite with generated credentials?

We're not doing it because we wanted to maintain compatibility across services, and discussed on the Discord's [dc24-channel](https://github.com/Disconnect24/dc24-channel) discussion channel we would just patch URLs.

If you are generating, we will by all means begin dynamically patching with our own methods and reserving the mlid.

**Comment by TheMrIron2** [comment]
Enjoy trying to convince the RiiConnect24 team to use dynamic code, Poke - if you can get them to do so, it would be great for our project and honestly for the safety of the entire mail system, but I get this sneaking suspicion it won't be a straightforward decision like it should be with the RC devs.

**Comment by spotlightishere** [comment]
Oi, don't antagonize them. ;p

I know both here know the issues with their mail system, reasons why Mail-Go wasn't made with authentication in the first place and why the patcher is reading their mail's authentication in the first place.

Perhaps in a future IOS patch for DC24 we'll patch the default account generation URL and have that as a possibility.

**Comment by InternalLoss** [comment]
>To confirm I'm not misreading: you're telling us that the entire issue (short of verification of mlid) isn't needed, because your patcher is going to overwrite with generated credentials?

The issue is practically non-existant. I can confirm the patcher has a way to send the MLID to our server, and insert the supplied mlchkid/passwd to the file and correctly sign.

@TheMrIron2 The back-end server-side method for account generation and insertion has been coded by yours truly; I personally ensured that the service works and the only current issues with our patcher is IOS patching since it's not as simple as we first thought. I actually refused someone's idea to do the IOS patching in a shoddy way, rather instead patching correctly.

**Comment by InternalLoss** [comment]
>We're not doing it because we wanted to maintain compatibility across services, and discussed on the Discord's Disconnect24/dc24-installer channel we would just patch URLs.

Surely if the channel supported alternative services this is irrelevant? I don't see why we should "maintain compatibility" and not enforce more secure methods of doing things. If DC24 makes a more secure and ultimately *better* way of authenticating mail, then RC24 and other services should better get in gear and either adopt your Mail code or work out ways to implement it into their service. Difference by design is welcome in this community and if you make something more secure then people will change it.

**Comment by spotlightishere** [comment]
Alrighty. We'll continue down that path; thanks for clarifying.
